DROP DATABASE IF EXISTS deliverydb;
CREATE DATABASE IF NOT EXISTS deliverydb;
USE deliverydb;
CREATE TABLE IF NOT EXISTS customers (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    demand INT
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS vehicles (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    capacity INT,
    fuel_consumption DECIMAL(4, 2) NOT NULL
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS times (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    minutes INT
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS goods (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(4, 2) NOT NULL,
    max_amount_per_ton INT NOT NULL
)  ENGINE=INNODB;
