DROP DATABASE IF EXISTS deliverydb;
CREATE DATABASE IF NOT EXISTS deliverydb;
USE deliverydb;
CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    demand INT,
    status VARCHAR(255) NOT NULL,
    group_nr INT NOT NULL,
    depot BOOLEAN
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    capacity INT,
    fuel_consumption DECIMAL(4, 2) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT "available",
    rating DECIMAL(12, 8) NOT NULL,
    lunch_start VARCHAR(255),
    return_time INT DEFAULT 0
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS groups (
    id INT PRIMARY KEY,
    rating DECIMAL(12, 8) NOT NULL
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS times (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    minutes INT
)  ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS goods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(4, 2) NOT NULL,
    max_amount_per_ton INT NOT NULL
)  ENGINE=INNODB;
